# ---------- DATA: focal tumour cells and their 63-cell neighbourhoods ----------
import os, glob
import numpy as np, pandas as pd
from scipy.spatial import cKDTree

TYPES = ['tumour_like', 'tcell', 'host']          # neighbour classes generated by the model


def load_cells():
    cands = sorted(glob.glob('morphix_pfish_cells*.csv.gz'), key=os.path.getmtime)
    if not cands:
        from google.colab import files
        print('Upload the morphix_pfish_cells file from the SUCCESSFUL Step 2 run '
              '(it may be named "morphix_pfish_cells (1).csv.gz"):')
        up = files.upload()
        cands = [n for n in up if n.startswith('morphix_pfish_cells')]
    fn = cands[-1]
    cells = pd.read_csv(fn, index_col='cell_id')
    cells['gene'] = cells['gene'].fillna('').astype(str)
    if not (cells.cell_class == 'tumour').any():
        raise ValueError(f'{fn} has no tumour cells (old file from the failed run). Delete it and upload the newer one.')
    print('using', fn)
    return cells


def assign_classes(cells):
    """Same rule as the Step 3 signal check: 'other' cells with tumour-like counts are tumour-like,
    low-count 'other' cells (mostly mouse host) are 'host'."""
    tc = np.log10(cells['total_counts'] + 1)
    thr = np.quantile(tc[cells.cell_class == 'tumour'], 0.05)
    cls = np.where(cells.cell_class == 'tcell', 'tcell',
                   np.where((cells.cell_class == 'tumour') | (tc >= thr), 'tumour_like', 'host'))
    cells['ntype'] = pd.Categorical(cls, categories=TYPES).codes.astype(np.int64)
    return thr


def block_split_xy(xy, test_frac, n_blocks, seed):
    rng = np.random.default_rng(seed)
    lo, hi = xy.min(0), xy.max(0)
    b = np.minimum(((xy - lo) / (hi - lo + 1e-9) * n_blocks).astype(int), n_blocks - 1)
    bid = b[:, 0] * n_blocks + b[:, 1]
    counts = np.bincount(bid, minlength=n_blocks ** 2)
    test, n = [], 0
    for i in rng.permutation(np.unique(bid)):
        if n >= test_frac * len(xy):
            break
        test.append(i); n += counts[i]
    return np.isin(bid, test)


def build_patches(cells, cfg, rng):
    XY = cells[['x', 'y']].values
    tree = cKDTree(XY)
    d2, _ = tree.query(XY, k=2)
    unit = float(np.median(d2[:, 1]))
    n_nb = cfg['n_neighbours']
    is_test = block_split_xy(XY, cfg['test_frac'], cfg['n_blocks'], cfg['seed'])

    # conditions: 0 = unknown (unlabelled tumour-like cells), 1 = Control, 2.. = knockouts with enough cells
    tum = cells[(cells.cell_class == 'tumour') & ~cells.gene.isin(['multiple', 'none', ''])]
    vc = tum.gene.value_counts()
    genes = [g for g, n in vc.items() if g != 'Control' and n >= cfg['min_cells_per_gene']]
    cond_names = ['unknown', 'Control'] + sorted(genes)
    cond_id = {g: i for i, g in enumerate(cond_names)}
    cond = np.full(len(cells), -1)
    labelled = (cells.cell_class == 'tumour').values & cells.gene.isin(cond_names[1:]).values
    cond[labelled] = [cond_id[g] for g in cells.gene.values[labelled]]
    unlab = (cells.cell_class == 'other').values & (cells.ntype.values == TYPES.index('tumour_like'))
    cond[unlab] = 0

    focal = np.flatnonzero(cond >= 0)
    d, nb = tree.query(XY[focal], k=n_nb + 1)
    nb = nb[:, 1:]
    clean = (is_test[nb] == is_test[focal][:, None]).all(1)       # patch entirely inside its split
    focal, nb = focal[clean], nb[clean]
    pos = ((XY[nb] - XY[focal][:, None, :]) / unit).astype(np.float32)   # neighbours relative to the focal cell
    typ = cells.ntype.values[nb].astype(np.int64)
    c = cond[focal]
    te = is_test[focal]

    # cap the number of unlabelled patches (they teach general structure; labelled ones teach knockout effects)
    keep = np.ones(len(focal), bool)
    for split in [False, True]:
        idx = np.flatnonzero((c == 0) & (te == split))
        cap = cfg['max_unlabelled'] if not split else cfg['max_unlabelled'] // 4
        if len(idx) > cap:
            keep[rng.choice(idx, len(idx) - cap, replace=False)] = False
    data = dict(pos=pos[keep], typ=typ[keep], cond=c[keep], test=te[keep], focal=focal[keep])
    return data, cond_names, unit
